### ISSUE TITLE
Genius

### ISSUE THREAD

**Issue by gedw99** [acaloiaro/hugo-htmx-go-template#3]
So happy to see this.

always wanted to try this combo.

if you have a roadmap so i can contribute it would be awesome.

man very happy that it has both go templates and templ. 

Templ is impressive but sometime you just want go templates when you want to avoid code gen.

**Comment by gedw99** [comment]
got it working on my side. works great.

**Comment by acaloiaro** [comment]
Glad you got it working! 

As for a roadmap, I hadn't given in much thought. If you have ideas for what would make it more helpful, that would be great. My initial plan for this was just to be a nice project bootstrapper to get my personal work off the ground using this pattern. Maybe there could be more to it?
