### ISSUE TITLE
Show missed mux Handler Func in server.go

### ISSUE THREAD

**Issue by gedw99** [acaloiaro/hugo-htmx-go-template#5]
i noticed when making a new form submit that server.go does not have a handler you get silent failure for a missed handler

server.go handler code
```go
// Add any number of handlers for custom endpoints here
	mux.HandleFunc("/goodbyeworld.html", cors(templ.Handler(partials.GoodbyeWorld())))
	mux.HandleFunc("/hello_world", cors(http.HandlerFunc(helloWorld)))
	mux.HandleFunc("/hello_world_form", cors(http.HandlerFunc(helloWorldForm)))

	// mux.HandleFunc("/test_hello_world_form", cors(http.HandlerFunc(helloWorldForm)))
```

When i added the "test_hello_world_form" everything worked, but i needed to remember that, because you get no feedback on terminal or Web GUI. Web GUI  just fails silently.

Maybe we could have a missed handler check or something and show it in terminal or Web GUI ? what do you think ?

**Comment by acaloiaro** [comment]
> When i added the "test_hello_world_form" everything worked, but i needed to remember that, because you get no feedback on terminal or Web GUI. Web GUI just fails silently.

Sorry I'm not sure that I follow. What was your expectation of what would happen in this situation? The only change from the original I'm seeing is a commented out line of code.

**Comment by gedw99** [comment]
That’s ok I worked it out later.

There is no bug.
