### ISSUE TITLE
using standard go templates

### ISSUE THREAD

**Issue by gedw99** [acaloiaro/hugo-htmx-go-template#6]
any way we can also use standard go templates ?

templ is cool, but would be nice to also be also be able to use standard ones without need for complation.

**Comment by acaloiaro** [comment]
Sorry @gedw99 I just re-read that code and realized that while it was previously a standard `html/template`, it is now indeed a `templ` template like you said.

I'd be happy to accept a PR that adds a simple `html/template` example.

**Comment by gedw99** [comment]
Didn’t the project use standard templates in the past ? 

If so we could look back and then add standard templates again.

**Comment by gedw99** [comment]
Shows when it used to use normal go html templates. I would like to have both.

https://github.com/acaloiaro/hugo-htmx-go-template/commit/e883eefcfc0f3b8ee26d3150f5469c44f7bbeb22#diff-366e46a40f6f60b4f7614eb0976bb51820364bf5ca6ccc4787eb49d7bdbef3e6

**Comment by acaloiaro** [comment]
Turns out I'm not crazy. The hello world example still uses `html/template`: https://github.com/acaloiaro/hugo-htmx-go-template/blob/main/server.go#L60
